services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    volumes:
      - ./frontend:/app          # monta el código local
      - /app/node_modules        # evita mezclar node_modules
    command: yarn dev -p 3000
    ports:
      - "3000:3000"
