services:
  
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    volumes:
      - ./backend:/app           # monta tu código local
      - /app/node_modules        # evita mezclar node_modules
    command: yarn dev
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn dev -p ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"